version: '3.8'

services:

  d7add2192805162d:
    build: ./d7add2192805162d
    container_name: hackforge_d7add2192805162d
    ports:
      - "8080:80"
    volumes:
      - ./d7add2192805162d/app:/var/www/html
      - ./d7add2192805162d/flag.txt:/var/www/html/flag.txt:ro
    environment:
      - MACHINE_ID=d7add2192805162d
      - FLAG_LOCATION=/var/www/html/flag.txt
    restart: unless-stopped
