version: '3.8'

services:
  web:
    build: .
    container_name: hackforge_58e7e5331ef3b59d
    ports:
      - "8082:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - hackforge_58e7e5331ef3b59d
    restart: unless-stopped

networks:
  hackforge_58e7e5331ef3b59d:
    driver: bridge

