version: '3.8'

services:

  21f07f74ee737fac:
    build: ./21f07f74ee737fac
    container_name: hackforge_21f07f74ee737fac
    ports:
      - "8080:80"
    volumes:
      - ./21f07f74ee737fac/app:/var/www/html
      - ./21f07f74ee737fac/flag.txt:/var/www/html/flag.txt:ro
    environment:
      - MACHINE_ID=21f07f74ee737fac
      - FLAG_LOCATION=/var/www/html/flag.txt
    restart: unless-stopped
