version: '3.8'

services:

  98888280c4a552f7:
    build: ./98888280c4a552f7
    container_name: hackforge_98888280c4a552f7
    ports:
      - "8080:80"
    volumes:
      - ./98888280c4a552f7/app:/var/www/html
      - ./98888280c4a552f7/flag.txt:/var/www/html/flag.txt:ro
    environment:
      - MACHINE_ID=98888280c4a552f7
      - FLAG_LOCATION=/var/www/html/flag.txt
    restart: unless-stopped
