version: '3.8'

services:

  ae19872bcbbfb961:
    build: ./ae19872bcbbfb961
    container_name: hackforge_ae19872bcbbfb961
    ports:
      - "8080:80"
    volumes:
      - ./ae19872bcbbfb961/app:/var/www/html
      - ./ae19872bcbbfb961/flag.txt:/var/www/html/flag.txt:ro
    environment:
      - MACHINE_ID=ae19872bcbbfb961
      - FLAG_LOCATION=/var/www/html/flag.txt
    restart: unless-stopped
