version: '3.8'

services:

  6f25e6f98078ff98:
    build: ./6f25e6f98078ff98
    container_name: hackforge_6f25e6f98078ff98
    ports:
      - "8080:80"
    volumes:
      - ./6f25e6f98078ff98/app:/var/www/html
      - ./6f25e6f98078ff98/flag.txt:/var/www/html/flag.txt:ro
    environment:
      - MACHINE_ID=6f25e6f98078ff98
      - FLAG_LOCATION=/var/www/html/flag.txt
    restart: unless-stopped

  5c82b9804f4cb764:
    build: ./5c82b9804f4cb764
    container_name: hackforge_5c82b9804f4cb764
    ports:
      - "8081:80"
    volumes:
      - ./5c82b9804f4cb764/app:/var/www/html
      - ./5c82b9804f4cb764/flag.txt:/var/www/html/flag.txt:ro
    environment:
      - MACHINE_ID=5c82b9804f4cb764
      - FLAG_LOCATION=/var/www/html/flag.txt
    restart: unless-stopped

  fe09828f4588b857:
    build: ./fe09828f4588b857
    container_name: hackforge_fe09828f4588b857
    ports:
      - "8082:80"
    volumes:
      - ./fe09828f4588b857/app:/var/www/html
      - ./fe09828f4588b857/flag.txt:/var/www/html/flag.txt:ro
    environment:
      - MACHINE_ID=fe09828f4588b857
      - FLAG_LOCATION=/var/www/html/flag.txt
    restart: unless-stopped

  c578675ae2eff009:
    build: ./c578675ae2eff009
    container_name: hackforge_c578675ae2eff009
    ports:
      - "8083:80"
    volumes:
      - ./c578675ae2eff009/app:/var/www/html
      - ./c578675ae2eff009/flag.txt:/var/www/html/flag.txt:ro
    environment:
      - MACHINE_ID=c578675ae2eff009
      - FLAG_LOCATION=/var/www/html/flag.txt
    restart: unless-stopped
